Assignment1/Models/DoctorModel.cs
namespace Assignment1.Models
{
    public class DoctorModel
    {
        public static string FeverCheck(float temperature)
        {
            if (temperature < 37 || temperature > 37.7)
            {
                return "You do have a fever!";
            }

            return "You do not have a fever";
        }
    }
}

Assignment1/Models/ProjectViewModel.cs
using System.Collections.Generic;

namespace Assignment1.Models
{
    public class ProjectViewModel
    {
        public string Url;
        public string Title;
        public string Description;
    }
}

Assignment1/Controllers/DoctorController.cs
using Assignment1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment1.Controllers
{
    public class DoctorController : Controller
    {
        // GET
        public IActionResult FeverCheck()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult FeverCheck(float temperature)
        {
            if(temperature != 0)
               ViewBag.Message = DoctorModel.FeverCheck(temperature);
            return View();
        }
    }
}

Assignment1/Controllers/GuessingGameController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Assignment1.Controllers
{
    public class GuessingGameController : Controller
    {
        // GET
        public IActionResult Index()
        {
            if (HttpContext.Session.TryGetValue("randomNumber", out _)) return View();
            SetRandomNumber();
            return View();
        }

        private void SetRandomNumber()
        {
            var randomNumber = new Random().Next(1, 100);
            HttpContext.Session.SetInt32(key: "randomNumber", value: randomNumber);
        }

        [HttpPost]
        public IActionResult Index(int number)
        {
            var randomNumber = HttpContext.Session.GetInt32("randomNumber");
            var correct = number == randomNumber;
            if (correct)
            {
                SetRandomNumber();
                ViewBag.Message = "Correct";
            }
            else
            {
                ViewBag.Message = number < randomNumber ? "Your guess is to low." : "your guess is to high";
            }
            return View();
        }
    }
}

Assignment1/Controllers/HomeController.cs
using System.Collections.Generic;
using Assignment1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Assignment1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }        
        public IActionResult Projects()
        {
            //var viewModel = new ProjectViewModel();
            var viewModel = new List<ProjectViewModel>
            {
                new ProjectViewModel()
                {
                    Description = "Hänga gubbe",
                    Title = "LexiconHangman",
                    Url = "https://github.com/weinitz/LexiconHangman"
                },
                new ProjectViewModel()
                {
                    Description = "Kalkulator",
                    Title = "LexiconCalculator",
                    Url = "https://github.com/weinitz/LexiconCalculator"
                },
                new ProjectViewModel()
                {
                    Description = "Grupparbete",
                    Title = "LexiconTodoIt",
                    Url = "https://github.com/weinitz/LexiconTodoIt"
                },
                new ProjectViewModel()
                {
                    Description = "Tre i rad",
                    Title = "TicTacToe",
                    Url = "https://github.com/weinitz/TicTacToe"
                },
                new ProjectViewModel()
                {
                    Description = "Vending Machine",
                    Title = "Vending Machine",
                    Url = "https://github.com/weinitz/Vending-Machine"
                },
                new ProjectViewModel()
                {
                    Description = "Grundläggande html och css",
                    Title = "Basic-HTML-Fundamentals",
                    Url = "https://github.com/weinitz/Basic-HTML-Fundamentals"
                }
            };

            return View(viewModel);
        }
    
    }
}

Assignment1/Views/Doctor/FeverCheck.cshtml
@model object

@{
    ViewBag.Title = "Doctor";
    Layout = "_Layout";
}

<h2>Doctor</h2>
@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}
else
{
    <form asp-controller="Doctor" asp-action="FeverCheck" method="post">
        <label>temperature:</label>
        <input type="number" name="temperature"/>
        <input type="submit" value="Send"/>
    </form>
}

Assignment1/Views/GuessingGame/Index.cshtml
@model object

@{
    ViewBag.Title = "Guessing game";
    Layout = "_Layout";
}

<h2>Guess a number 1-100</h2>
@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

    <form asp-controller="GuessingGame" asp-action="Index" method="post">
        <label>Guess number:</label>
        <input type="number" name="number"/>
        <input type="submit" value="Send"/>
    </form>

Assignment1/Views/Home/About.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Om</h2>
<p>
Hej.
Här har ni en kille på 31 år med stort intresse för programmering.
Jag läster dotnet på lexicon och tycker att det är väldigt roligt. 
Nya tekniker och lösningar är något som driver mig och jag spenderar mycket tid på att leta nya projekt på Github.
</p>

Assignment1/Views/Home/Contact.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Kontakt</h2>
<dl>
    <dt>Tel</dt>
    <dd>072-9939555</dd>
    <dt>Mail</dt>
    <dt><img src="~/images/mail.png"  alt="email"/></dt>
</dl>

Assignment1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Start</h1>

Assignment1/Views/Home/Projects.cshtml
@model List<Assignment1.Models.ProjectViewModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}


<h2>Projects</h2>
@foreach (var project in Model)
{
    <div>
        <h2>
            <a href="@project.Url">@project.Title</a>
        </h2>
        <p>
            @project.Description
        </p>
    </div>
}

Assignment1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="~/css/main.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
</head>
<body>
<section>
    <div class="wrapper">
        <header>
            <nav class="container">
                <div class="logo">
                </div>
                <div class="start">
                    <a asp-controller="Home" asp-action="Index" class="navLinks">Start</a>
                </div>
                <div class="about">
                    <a asp-controller="Home" asp-action="About" class="navLinks">About Me</a>
                </div>
                <div class="contact">
                    <a asp-controller="Home" asp-action="Contact" class="navLinks">Contact Me</a>
                </div>
                <div class="projects">
                    <a asp-controller="Home" asp-action="Projects" class="navLinks">Projects</a>
                </div>
            </nav>
        </header>
        <main>
            @RenderBody()
        </main>
        <footer>
            <span>&copy; Tim Weinitz @DateTime.Now.ToString("yyyy-MM-dd")</span>
        </footer>
    </div>
</section>
</body>
</html>